### ISSUE TITLE
Duplicate Keys

### ISSUE THREAD

**Issue by Guergeiro** [Cepos-e-Mabecos/bd2-group2#26]
Inserts don't handle duplicate keys. Although it is pretty much unlikely this would happen, it should be handled nevertheless.
### Solution 1
1. Generate ID.
2. `try` to insert new row.
3. `catch` if a duplicate key `error` was `thrown`.
4. Re-do 1 to 4 until no `error` is `thrown`.
### Solution 2
1. Generate ID.
2. Search for a row with generated ID.
3. Re-do 1 to 3 until 2 returns no row.
4. Insert new row with generated ID.

_Note:_ To help our final project presentation, it would be more useful to do **Solution 1**, even though I'm in favor of **Solution 2**.

**Comment by diogofalken** [comment]
The chances of two keys be the same are 1 346 274 334 462 890 625‬, really unlikely, I think this is not our top priority right now.
But it's a nice update to implement!
